### ISSUE TITLE
How to read textarea variable?

### ISSUE THREAD

**Issue by dagoldman** [boutell/cgic#21]
Is there a cgic function to read a textarea variable? In other words, the front end HTML form has a textarea field. The form variables are submitted with POST. Can CGIC correctly parse the textarea cgi variable? Is cgiFormString() used? If not, any other suggestions? Thanks

**Comment by tenox7** [comment]
Yes, example:
https://github.com/tenox7/wfm/blob/00e8f239647ca940db8e0cb497eee8f87ab0d508/fileio.c#L132

**Comment by dagoldman** [comment]
Thank you for the quick and helpful answer.
